services:
  db:
    image: postgres:15-alpine
    container_name: gamerfinder_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    container_name: gamerfinder_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:mysecretpassword@db:5432/postgres
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - db
      - mailpit
    restart: always

  mailpit:
    image: axllent/mailpit:latest
    container_name: gamerfinder_mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always

volumes:
  postgres_data: