"""Add pro trial and expiry fields to user

Revision ID: 0ee788ea80dd
Revises: bde322e05882
Create Date: 2026-07-20 15:41:24.889020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ee788ea80dd'
down_revision: Union[str, Sequence[str], None] = 'bde322e05882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_members', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('users', sa.Column('pro_trial_used', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('pro_expiry_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('pro_trial_dismissed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pro_trial_dismissed_at')
    op.drop_column('users', 'pro_expiry_date')
    op.drop_column('users', 'pro_trial_used')
    op.alter_column('chat_members', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
