"""add admin and avatar to chat

Revision ID: 2734748937d1
Revises: ae63da7b730b
Create Date: 2026-07-13 00:05:01.624569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2734748937d1'
down_revision: Union[str, Sequence[str], None] = 'ae63da7b730b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_members')
    op.add_column('chats', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.add_column('chats', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('description', sa.String(), nullable=True))
    op.create_foreign_key(None, 'chats', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'description')
    op.drop_column('chats', 'avatar_url')
    op.drop_column('chats', 'admin_id')
    op.create_table('chat_members',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('chat_members_chat_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chat_members_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_members_pkey'))
    )
    # ### end Alembic commands ###
