"""add_message_status

Revision ID: a45321f89668
Revises: ba520d43c7c8
Create Date: 2026-07-04 20:20:46.551369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45321f89668'
down_revision: Union[str, Sequence[str], None] = 'ba520d43c7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chat_members', 'users', ['user_id'], ['id'])
    op.add_column('messages', sa.Column('status', sa.String(), nullable=True))
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'status')
    op.drop_constraint(None, 'chat_members', type_='foreignkey')
    # ### end Alembic commands ###
