"""add_is_admin_to_chat_member

Revision ID: bde322e05882
Revises: e4d7a2a61b4d
Create Date: 2026-07-17 12:16:11.552645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bde322e05882'
down_revision: Union[str, Sequence[str], None] = 'e4d7a2a61b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_members', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_members', 'is_admin')
    # ### end Alembic commands ###
