"""add_reply_to_id_to_message

Revision ID: bdfc81a62979
Revises: a45321f89668
Create Date: 2026-07-08 00:14:01.012684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdfc81a62979'
down_revision: Union[str, Sequence[str], None] = 'a45321f89668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_to_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'reply_to_id')
    # ### end Alembic commands ###
